### ISSUE TITLE
V3 KudosBoards example uses service "Communities" for as_event grant but that's wrong, right?

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/connections-msp#21]
```
 {    "name": "Kudos Boards",
    "title": "Kudos Boards",
    "description": "Kudos Boards community and activity stream extensions",
    "app_id" : "com.isw.kudosboards",
    "services": [
        "Communities"
    ],
    "state": "disabled",
    "extensions": [
{
            "ext_id": "com.isw.kudosboards.as_event",
            "name": "Kudos Boards Activity Stream Events",
            "description": "Provide activity stream entries for Kudos Board events",
            "type": "gadget",
            "payload": {
                "extends": "as_event",
                "mime_type": "",
                "icon": "https://kudosboards.com/favicon.ico",
                "tooltip": "AS entry for Board",
                "description": "AS entry for Boards",
                "new_window": "false",
                "text": "Boards AS",
                "url": "https://kudosboards.com/stream/smartcloud"
            },
            "state": "enabled"
        }
```
See here:
https://github.com/hclcnx/connections-msp/blob/master/appcatalog-v3/com.isw.kudosboards.json

What is the correct service for the extension?

**Comment by BerndGewehr** [comment]
It looks like CNX 6.5MT requests extensions via /manage but doesn't get a response:

![image](https://user-images.githubusercontent.com/21081707/87319146-8a217180-c529-11ea-8611-ea7c3ad52901.png)
![image](https://user-images.githubusercontent.com/21081707/87319168-91487f80-c529-11ea-83ec-33ab39ee1ef3.png)

**Comment by BerndGewehr** [comment]
```
{
    "app_id": "xapps.v3",
    "name": "Xapps EE",
    "title": "Xapps EE",
    "description": "Extensions for domino integration to CNX EE",
    "services": [
        "Connections"
    ],
    "state": "enabled",
    "extensions": [
        {
            "ext_id": "de.voessing.xapps.EE",
            "name": "xapps Embedded Experience",
            "description": "xapps Embedded Experience",
            "type": "gadget",
            "payload": {
                "extends": "as_event",
                "icon": "https://xapps.voessing.de/ee/selfservice.png",
                "description": "AS entry for Xapps",
                "url": "https://xapps.voessing.de/ee/ee.html"
            },
            "state": "enabled"
        }
    ]
}
```

I still see an error on EE:
![image](https://user-images.githubusercontent.com/21081707/87319341-cbb21c80-c529-11ea-843f-9dd900fb1435.png)

![image](https://user-images.githubusercontent.com/21081707/87319353-d076d080-c529-11ea-8b47-cd6ccd1e1f4f.png)

**Comment by hclcnxdev** [comment]
/manage is a cloud only uri - in MT requests are made to /appregistry/api/v3/(services|applications|extensions).  The activity stream extensions are requested by type i.e. gadget and not the service itself. Since the v3 appregistry does not have the same service list as v2, we published the example using Communities, since the community widgets for the app are usually in the same app extension definition.

**Comment by BerndGewehr** [comment]
I made this error screenshot of devpanel in 6.5MT. So it requested /manage without response. Something the MSP can fix or must you do it?

**Comment by BerndGewehr** [comment]
The other thread: what I understood  now is that regardless of "service" we can group several extensions into one app although being documented on different services. That's good to know - if it would work correctly.

**Comment by hclcnxdev** [comment]
The important thing is by what criteria does the code consuming the extension locate the list of the available extensions. So you can only group them under the same app if the consumer(s) are looking for them based on the service property and they all relate to that service, since the service is an app level property. But as you can see the consuming code can query by some other extension specific property like type or ext_id in which case service is unimportant to locating the extension.

**Comment by BerndGewehr** [comment]
Now please back to the one Thread:

Why does cnx 6.5MT request a url from the /manage URI?

**Comment by BerndGewehr** [comment]
@hclcnxdev I found the reason for this with help from @danieleVistalli. The "old" activity stream posts, migrated from IBM Connections Cloud, still contain the https://apps.ce.collabserv.com xml gadget url and mislead the process on MSP cloud.

We have to fix the migrated data so that only relative links are used like /connections/... then this will disappear.

Unclear so far how to search and replace - which db2 table etc.
